services:
  # Web Service (Spring Boot App with Docker)
  - type: web
    name: inventory-manager
    runtime: docker
    region: oregon
    plan: free
    envVars:
      - key: PGHOST
        fromDatabase:
          name: inventory-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: inventory-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: inventory-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: inventory-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: inventory-db
          property: password

databases:
  # PostgreSQL Database
  - name: inventory-db
    plan: free
    databaseName: inventorydb
    user: inventoryuser
