services:
  # Web Service (Spring Boot App)
  - type: web
    name: inventory-manager
    env: java
    region: oregon
    plan: free
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/inventory-manager-1.0-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 11
      - key: PGHOST
        fromDatabase:
          name: inventory-db
          property: host
      - key: PGPORT
        fromDatabase:
          name: inventory-db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: inventory-db
          property: database
      - key: PGUSER
        fromDatabase:
          name: inventory-db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: inventory-db
          property: password

databases:
  # PostgreSQL Database
  - name: inventory-db
    plan: free
    databaseName: inventorydb
    user: inventoryuser
