package dev.inventorymanager.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import javax.persistence.*;
import java.math.BigDecimal;
import java.util.List;

/**
 * Entity representing an inventory item/product.
 *
 * This class stores information about products in the inventory system including:
 * - Basic product information (name, SKU)
 * - Current stock quantity
 * - Pricing information
 * - Ownership (which user owns this item)
 * - Transaction history
 *
 * Items are owned by users in a multi-tenant system. Each user can only see
 * and manage their own items.
 *
 * Database Table: items
 */
@Entity
@Table(name = "items")
public class Item {

    /**
     * Unique identifier for this item.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable name of the product.
     * Example: "Wireless Mouse", "Laptop Charger", "Office Chair"
     */
    private String name;

    /**
     * Stock Keeping Unit - a unique identifier for this product.
     * Used for inventory tracking and identification.
     * Example: "WM-001", "LC-XYZ", "OC-ERGONOMIC"
     */
    private String sku;

    /**
     * Current quantity/stock level of this item.
     * Updated automatically when buy/sell transactions are processed.
     * Should not be negative.
     */
    private Integer quantity;

    /**
     * Current price of the item.
     * Using BigDecimal for precise monetary calculations.
     * This can represent either purchase price or selling price depending on context.
     */
    private BigDecimal price;

    /**
     * The user who owns this item.
     * Many items can belong to one user (Many-to-One relationship).
     * JsonIgnore prevents circular references during JSON serialization.
     */
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = true)
    @JsonIgnore
    private User user;

    /**
     * List of all transactions associated with this item.
     * One item can have many transactions (One-to-Many relationship).
     * CascadeType.ALL: operations on item cascade to transactions
     * orphanRemoval: deleting an item deletes all its transactions
     * JsonIgnore prevents including full transaction history in item JSON responses
     */
    @OneToMany(mappedBy = "item", cascade = CascadeType.ALL, orphanRemoval = true)
    @JsonIgnore
    private List<Transaction> transactions;

    /**
     * Default constructor required by JPA.
     */
    public Item() {}

    /**
     * Constructs a new item with the specified parameters.
     *
     * @param name Product name
     * @param sku Stock keeping unit
     * @param quantity Initial quantity
     * @param price Price of the item
     */
    public Item(String name, String sku, Integer quantity, BigDecimal price) {
        this.name = name;
        this.sku = sku;
        this.quantity = quantity;
        this.price = price;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public List<Transaction> getTransactions() {
        return transactions;
    }

    public void setTransactions(List<Transaction> transactions) {
        this.transactions = transactions;
    }
}
