package dev.inventorymanager.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import javax.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Entity representing an inventory transaction (buy or sell).
 *
 * This class tracks all inventory movements with complete audit trail including:
 * - What item was transacted
 * - Who performed the transaction
 * - Type of transaction (BUY or SELL)
 * - Quantity and pricing details
 * - Inventory snapshots before and after the transaction
 * - Transaction status and optional notes
 *
 * Transactions are immutable once created (should not be modified).
 * For corrections, create a reversal transaction instead.
 *
 * Database Table: transactions
 */
@Entity
@Table(name = "transactions")
public class Transaction {

    /**
     * Unique identifier for this transaction.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "transaction_seq")
    @SequenceGenerator(name = "transaction_seq", sequenceName = "transactions_id_seq", allocationSize = 1)
    private Long id;

    /**
     * The inventory item being transacted.
     * Many transactions can reference one item (Many-to-One relationship).
     * This field is required and cannot be null.
     *
     * JsonIgnoreProperties prevents circular reference by ignoring the 'transactions'
     * field when serializing the item.
     */
    @ManyToOne
    @JoinColumn(name = "item_id", nullable = false)
    @JsonIgnoreProperties({"transactions", "user"})
    private Item item;

    /**
     * The user who created/performed this transaction.
     * Many transactions can belong to one user (Many-to-One relationship).
     * Can be null for system-generated transactions.
     *
     * JsonIgnoreProperties prevents circular reference by ignoring the 'transactions'
     * and 'items' fields when serializing the user.
     */
    @ManyToOne
    @JoinColumn(name = "user_id", nullable = true)
    @JsonIgnoreProperties({"transactions", "items", "password"})
    private User user;

    /**
     * Type of transaction (BUY or SELL).
     * Stored as a string in the database for readability.
     * - BUY: Increases inventory quantity
     * - SELL: Decreases inventory quantity
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TransactionType type;

    /**
     * Current status of the transaction.
     * Defaults to COMPLETED for backward compatibility.
     * Possible values: PENDING, COMPLETED, FAILED, REVERSED
     *
     * NOTE: Made nullable to allow migration of existing data
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = true)
    private TransactionStatus status = TransactionStatus.COMPLETED;

    /**
     * Number of units involved in this transaction.
     * Must be a positive integer.
     * For BUY: units purchased
     * For SELL: units sold
     */
    @Column(nullable = false)
    private Integer quantity;

    /**
     * Price per unit for this transaction.
     * Using BigDecimal for precise monetary calculations.
     * Should not be negative.
     */
    @Column(nullable = false)
    private BigDecimal pricePerUnit;

    /**
     * Total monetary amount for this transaction.
     * Calculated as: pricePerUnit * quantity
     * Automatically set during transaction creation.
     */
    @Column(nullable = false)
    private BigDecimal totalAmount;

    /**
     * Timestamp when this transaction was created.
     * Automatically set to current time during construction.
     */
    @Column(nullable = false)
    private LocalDateTime transactionDate;

    /**
     * Snapshot of the item's inventory quantity BEFORE this transaction was processed.
     * Used for audit trail and debugging.
     * Example: If inventory was 100 and we sell 10, inventoryBefore = 100
     */
    @Column(name = "inventory_before")
    private Integer inventoryBefore;

    /**
     * Snapshot of the item's inventory quantity AFTER this transaction was processed.
     * Used for audit trail and verification.
     * Example: If inventory was 100 and we sell 10, inventoryAfter = 90
     */
    @Column(name = "inventory_after")
    private Integer inventoryAfter;

    /**
     * Optional notes or comments about this transaction.
     * Maximum length: 1000 characters
     * Use cases: reason for transaction, customer info, special instructions, etc.
     */
    @Column(length = 1000)
    private String notes;

    /**
     * Default constructor required by JPA.
     * Initializes transaction date to current time.
     */
    public Transaction() {
        this.transactionDate = LocalDateTime.now();
    }

    /**
     * Constructs a new transaction with the specified parameters.
     * Automatically calculates totalAmount and sets transactionDate to now.
     *
     * @param item The inventory item being transacted
     * @param type The transaction type (BUY or SELL)
     * @param quantity Number of units
     * @param pricePerUnit Price per unit
     */
    public Transaction(Item item, TransactionType type, Integer quantity, BigDecimal pricePerUnit) {
        this.item = item;
        this.type = type;
        this.quantity = quantity;
        this.pricePerUnit = pricePerUnit;
        // Calculate total amount: price per unit * quantity
        this.totalAmount = pricePerUnit.multiply(BigDecimal.valueOf(quantity));
        this.transactionDate = LocalDateTime.now();
        this.status = TransactionStatus.COMPLETED;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Item getItem() {
        return item;
    }

    public void setItem(Item item) {
        this.item = item;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public TransactionType getType() {
        return type;
    }

    public void setType(TransactionType type) {
        this.type = type;
    }

    public TransactionStatus getStatus() {
        return status;
    }

    public void setStatus(TransactionStatus status) {
        this.status = status;
    }

    public Integer getInventoryBefore() {
        return inventoryBefore;
    }

    public void setInventoryBefore(Integer inventoryBefore) {
        this.inventoryBefore = inventoryBefore;
    }

    public Integer getInventoryAfter() {
        return inventoryAfter;
    }

    public void setInventoryAfter(Integer inventoryAfter) {
        this.inventoryAfter = inventoryAfter;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Integer getQuantity() {
        return quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getPricePerUnit() {
        return pricePerUnit;
    }

    public void setPricePerUnit(BigDecimal pricePerUnit) {
        this.pricePerUnit = pricePerUnit;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public LocalDateTime getTransactionDate() {
        return transactionDate;
    }

    public void setTransactionDate(LocalDateTime transactionDate) {
        this.transactionDate = transactionDate;
    }
}
