package dev.inventorymanager.model;

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Entity representing a user account in the system.
 *
 * This class handles user authentication and authorization:
 * - Authentication: username/password credentials
 * - Authorization: role-based access control
 * - Account management: creation date, enabled status
 * - Multi-tenancy: each user owns their own items and transactions
 *
 * The system uses Spring Security for authentication. Passwords should be
 * stored encrypted (BCrypt) before saving to database.
 *
 * Database Table: users
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * Unique identifier for this user.
     * Auto-generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "user_seq")
    @SequenceGenerator(name = "user_seq", sequenceName = "users_id_seq", allocationSize = 1)
    private Long id;

    /**
     * Unique username for login.
     * Must be unique across all users.
     * Used for authentication with Spring Security.
     */
    @Column(unique = true, nullable = false)
    private String username;

    /**
     * Encrypted password for authentication.
     * Should be stored as BCrypt hash, never plain text.
     * Example: "$2a$10$..." (BCrypt hash format)
     */
    @Column(nullable = false)
    private String password;

    /**
     * User's role for authorization purposes.
     * Default: "USER"
     * Used by Spring Security for role-based access control.
     * Common values: "USER", "ADMIN", "MANAGER"
     */
    @Column(nullable = false)
    private String role = "USER";

    /**
     * Timestamp when this user account was created.
     * Automatically set to current time during construction.
     */
    @Column(nullable = false)
    private LocalDateTime createdAt;

    /**
     * Whether this user account is active/enabled.
     * Default: true
     * If false, user cannot login (account disabled).
     * Useful for temporarily suspending accounts without deletion.
     */
    @Column(nullable = false)
    private boolean enabled = true;

    /**
     * All transactions created by this user.
     * One user can have many transactions (One-to-Many relationship).
     * LAZY fetch: transactions are loaded only when explicitly accessed
     * orphanRemoval: deleting user deletes all their transactions
     */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    private Set<Transaction> transactions = new HashSet<>();

    /**
     * All inventory items owned by this user.
     * One user can have many items (One-to-Many relationship).
     * LAZY fetch: items are loaded only when explicitly accessed
     * orphanRemoval: deleting user deletes all their items
     */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    private Set<Item> items = new HashSet<>();

    /**
     * Default constructor required by JPA.
     * Initializes createdAt to current time.
     */
    public User() {
        this.createdAt = LocalDateTime.now();
    }

    /**
     * Constructs a new user with username and password.
     * Sets createdAt to current time.
     *
     * @param username Unique username for login
     * @param password Password (should be encrypted before passing to this constructor)
     */
    public User(String username, String password) {
        this.username = username;
        this.password = password;
        this.createdAt = LocalDateTime.now();
    }

    // Getters and Setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole() {
        return role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public Set<Transaction> getTransactions() {
        return transactions;
    }

    public void setTransactions(Set<Transaction> transactions) {
        this.transactions = transactions;
    }

    public Set<Item> getItems() {
        return items;
    }

    public void setItems(Set<Item> items) {
        this.items = items;
    }
}
